name: 发送邮件通知

on:
  workflow_dispatch:
    inputs:
      changes:
        description: '变更的文件列表'
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: 发送邮件
        uses: actions/github-script@v6
        with:
          script: |
            const emailBody = `
            检测到以下文件发生变更：
            
            ${context.payload.inputs.changes}
            
            请查看最新变更。
            
            此邮件由 GitHub Actions 自动发送。
            `;
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'github-actions-workflow-email',
              workflow_id: 'email.yml',
              ref: 'main',
              inputs: {
                to: 'your-email@example.com',  # 替换为你的邮箱
                subject: '文件变更通知',
                body: emailBody
              }
            }); 
